- name: Update pacman cache
  pacman:
    update_cache: yes
  become: yes

- name: Install usefull packages
  pacman:
    name:
      - htop
      - tree
      - jq
      - mtr
      - which
  become: yes
