# Installation and setup
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: oh-my-zsh.yml

# Configuration
- name: Check if zshrc already exists
  stat:
    path: "{{ user_home }}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{ user_home }}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Create symlink to .zshrc
  file:
    src: "{{ dotfiles_home }}/.zshrc"
    dest: "{{ user_home }}/.zshrc"
    state: link
    force: yes

- name: Setup user shell
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    shell: "{{ lookup('pipe', 'which zsh') }}"
